
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :firebase_distribution do
    sh "flutter clean"
    sh "flutter build apk --release --flavor production --target lib/main_production.dart --no-tree-shake-icons"
    
    firebase_app_distribution(
    app: "1:856424660746:android:1a35094f721a418dd284f3",
    firebase_cli_token: ENV["FIREBASE_CLI_TOKEN"],
    android_artifact_type: "APK",
    android_artifact_path: "../build/app/outputs/flutter-apk/app-production-release.apk",
    release_notes: "Testing something with GitHub Actions, trying to push directly from master branch",
    testers: "hfthacker1@gmail.com",
  )
  
  end
end
